import 'package:flutter_test/flutter_test.dart';
import 'package:agora_token_generator/agora_token_generator.dart';

/// Runs AccessToken2 multi-service and compatibility tests.
void main() {
  const String appId = '970CA35de60c44645bbae8a215061b33';
  const String appCertificate = '5CFd2fd1755d40ecb72977518be15d3b';
  const String channelName = '7d72365eb983485397e3e3f9d460bdda';
  const int uid = 2882341273;
  const String uidString = '2882341273';
  const String roomUuid = '123';
  const int role = 1;
  const int tokenExpireSeconds = 600;
  const int issueTs = 1111111;
  const int salt = 1;
  const String userId = 'test_user';

  /// Creates a deterministic token for serialization comparisons.
  AccessToken createToken() {
    return AccessToken.create(
      appId,
      appCertificate,
      expire: tokenExpireSeconds,
      issueTs: issueTs,
      salt: salt,
    );
  }

  /// Creates a fully privileged RTC service.
  ServiceRtc createRtcService([
    String channel = channelName,
    Object account = uid,
  ]) {
    return ServiceRtc(channel, account)
      ..addPrivilege(
        ServiceRtc.privilegeJoinChannel,
        tokenExpireSeconds,
      )
      ..addPrivilege(
        ServiceRtc.privilegePublishAudioStream,
        tokenExpireSeconds,
      )
      ..addPrivilege(
        ServiceRtc.privilegePublishVideoStream,
        tokenExpireSeconds,
      )
      ..addPrivilege(
        ServiceRtc.privilegePublishDataStream,
        tokenExpireSeconds,
      );
  }

  group('AccessToken2 multi-service compatibility', () {
    // Verifies parsing a Token007 generated by the Python3 implementation.
    test('parses an existing standard token', () {
      const oldToken =
          '007eJxTYBBbsMMnKq7p9Hf/HcIX5kce9b518kCiQgSr5Zrp4X1Tu6UUGCzNDZwdjU1TUs0Mkk1MzExMk5ISUy0SjQxNDcwMk4yN3b8IMEQwMTAwMoAwBIL4CgzmKeZGxmamqUmWFsYmFqbGluapxqnGaZYpJmYGSSkpiVwMRhYWRsYmhkbmxgDCaiTj';
      final parsed = AccessToken.empty();

      expect(parsed.parse(oldToken), isTrue);
      expect(parsed.appId, appId);
      expect(parsed.issueTs, issueTs);
      expect(parsed.expire, tokenExpireSeconds);
      expect(parsed.salt, salt);
      expect(parsed.verifySignature(appCertificate), isTrue);
      final service = parsed.getServices(Service.RTC).single as ServiceRtc;
      expect(service.channelName, channelName);
      expect(service.uid, uidString);
      expect(
        service.privileges[ServiceRtc.privilegeJoinChannel],
        tokenExpireSeconds,
      );
    });

    // Verifies repeated ServiceTypes remain separate and preserve insertion order.
    test('round trips repeated RTC services', () {
      final token = createToken();
      final first = createRtcService();
      final second = ServiceRtc(channelName, uidString)
        ..addPrivilege(
          ServiceRtc.privilegeJoinChannel,
          tokenExpireSeconds + 200,
        )
        ..addPrivilege(
          ServiceRtc.privilegePublishDataStream,
          tokenExpireSeconds + 200,
        );
      token
        ..addService(ServiceRtm(uidString)
          ..addPrivilege(
            ServiceRtm.privilegeLogin,
            tokenExpireSeconds + 100,
          ))
        ..addService(first)
        ..addService(second);

      expect(token.services.first, isA<ServiceRtm>());
      expect(token.getServices(Service.RTC), hasLength(2));

      final parsed = AccessToken.empty();
      expect(parsed.parse(token.build()), isTrue);
      expect(parsed.verifySignature(appCertificate), isTrue);
      final rtcServices = parsed.getServices(Service.RTC).cast<ServiceRtc>();
      expect(rtcServices, hasLength(2));
      expect(rtcServices[0].channelName, channelName);
      expect(rtcServices[1].channelName, channelName);
      expect(rtcServices[1].uid, uidString);
      expect(
        rtcServices[1].privileges[ServiceRtc.privilegePublishDataStream],
        tokenExpireSeconds + 200,
      );
    });

    // Parses and verifies C++ Streaming, FCDN, and RTM2 services.
    test('parses extended services generated by C++', () {
      const token =
          '007eJxTYPj86Lzdz79M25wNn/lMfvu+TkfmdpiviKvChm8ZV3SWndytwGBpbuDsaGyakmpmkGxiYmZimpSUmGqRaGRoamBmmGRs7P5FgCGCiYGBkYGBgRkImYAsEJ8JTCowmKeYGxmbmaYmWVoYm1iYGluapxqnGqdZppiYGSSlpCRyMRhZWBgZmxgamRuzUaSbA6gXopuToSS1uCS+tDi1iJkB4jQmoGBuanFxYnqqbiKCmcTIAIEcDMUlRamJubqJLGD1jAxsDCD9uokAO/VDvQ==';
      final parsed = AccessToken.empty();

      expect(parsed.parse(token), isTrue);
      expect(parsed.verifySignature(appCertificate), isTrue);

      final streaming =
          parsed.getServices(Service.STREAMING).single as ServiceStreaming;
      expect(streaming.channelName, channelName);
      expect(streaming.account, uidString);
      expect(
        streaming.privileges[ServiceStreaming.privilegePublishMixStream],
        tokenExpireSeconds,
      );
      expect(
        streaming.privileges[ServiceStreaming.privilegePublishRawStream],
        tokenExpireSeconds,
      );

      final fcdn = parsed.getServices(Service.FCDN).single as ServiceFCdn;
      expect(fcdn.channelName, channelName);
      expect(fcdn.account, uidString);
      expect(
        fcdn.privileges[ServiceFCdn.privilegePublish],
        tokenExpireSeconds,
      );
      expect(fcdn.privileges[ServiceFCdn.privilegePlay], tokenExpireSeconds);

      final rtm2 = parsed.getServices(Service.RTM2).single as ServiceRtm2;
      expect(rtm2.userId, userId);
      expect(rtm2.permissions.details, {
        Rtm2Permissions.messageChannels: {
          Rtm2Permissions.read: ['message-a', 'message-b'],
        },
        Rtm2Permissions.streamChannels: {
          Rtm2Permissions.write: ['stream-a'],
        },
        Rtm2Permissions.users: {
          Rtm2Permissions.read: ['user-a'],
        },
      });
      expect(
        rtm2.privileges[ServiceRtm2.privilegeLogin],
        tokenExpireSeconds,
      );
    });

    // Verifies deterministic Streaming and FCDN generation and UID conversion against C++.
    test('round trips extended service numeric UIDs', () {
      final streamingUid = ServiceStreaming.withUid(channelName, uid)
        ..addPrivilege(
          ServiceStreaming.privilegePublishMixStream,
          tokenExpireSeconds,
        );
      final streamingWildcard = ServiceStreaming.withUid(channelName, 0)
        ..addPrivilege(
          ServiceStreaming.privilegePublishRawStream,
          tokenExpireSeconds,
        );
      final streamingAccount = ServiceStreaming(channelName, 'stream-account')
        ..addPrivilege(
          ServiceStreaming.privilegePublishMixStream,
          tokenExpireSeconds,
        )
        ..addPrivilege(
          ServiceStreaming.privilegePublishRawStream,
          tokenExpireSeconds,
        );
      final fcdnUid = ServiceFCdn.withUid(channelName, uid)
        ..addPrivilege(ServiceFCdn.privilegePublish, tokenExpireSeconds);
      final fcdnWildcard = ServiceFCdn.withUid(channelName, 0)
        ..addPrivilege(ServiceFCdn.privilegePlay, tokenExpireSeconds);
      final fcdnAccount = ServiceFCdn(channelName, 'fcdn-account')
        ..addPrivilege(ServiceFCdn.privilegePublish, tokenExpireSeconds)
        ..addPrivilege(ServiceFCdn.privilegePlay, tokenExpireSeconds);
      final token = createToken()
        ..addService(streamingUid)
        ..addService(streamingWildcard)
        ..addService(streamingAccount)
        ..addService(fcdnUid)
        ..addService(fcdnWildcard)
        ..addService(fcdnAccount);
      final encoded = token.build();
      final parsed = AccessToken.empty();

      expect(
        encoded,
        '007eAFTYLi93GuuUHrO9Fr71KVJKqfDby8RezlVfGLMO77DIl79U40UGCzNDZwdjU1TUs0Mkk1MzExMk5ISUy0SjQxNDcwMk4yN3b8IMEQwMTAwMjAwsDEwA2lGMF+BwTzF3MjYzDQ1ydLC2MTC1NjSPNU41TjNMsXEzCApJSWRi8HIwsLI2MTQyNwYpI+JSH0MQFuYoLYQq4ePobikKDUxVzcxOTm/NK+EjUx3spHkTjaS3cnDkJackgdzJQBJb19X',
      );
      expect(parsed.parse(encoded), isTrue);
      expect(
        parsed
            .getServices(Service.STREAMING)
            .cast<ServiceStreaming>()
            .map((service) => service.account),
        [uidString, '', 'stream-account'],
      );
      expect(
        parsed
            .getServices(Service.FCDN)
            .cast<ServiceFCdn>()
            .map((service) => service.account),
        [uidString, '', 'fcdn-account'],
      );
    });

    // Verifies ServiceType sorting without changing public insertion order.
    test('packs services in stable numeric type order', () {
      final forward = createToken()
        ..addService(createRtcService())
        ..addService(ServiceRtm(uidString)
          ..addPrivilege(ServiceRtm.privilegeLogin, tokenExpireSeconds));
      final reverseRtm = ServiceRtm(uidString)
        ..addPrivilege(ServiceRtm.privilegeLogin, tokenExpireSeconds);
      final reverse = createToken()
        ..addService(reverseRtm)
        ..addService(createRtcService());

      expect(forward.build(), reverse.build());
      expect(reverse.services.first, same(reverseRtm));
    });

    // Verifies known services before an unknown ServiceType remain available.
    test('retains known services before an unknown type', () {
      final token = createToken()
        ..addService(createRtcService())
        ..addService(Service(999)
          ..addPrivilege(Privileges.JOIN_CHANNEL, tokenExpireSeconds));
      final parsed = AccessToken.empty();

      expect(parsed.parse(token.build()), isTrue);
      expect(parsed.getServices(Service.RTC), hasLength(1));
      expect(parsed.getServices(999), isEmpty);
      expect(parsed.verifySignature(appCertificate), isTrue);
    });

    // Verifies parsing stops before services following an unknown payload.
    test('stops parsing after an unknown type', () {
      final token = createToken()
        ..addService(createRtcService())
        ..addService(Service(0)
          ..addPrivilege(Privileges.JOIN_CHANNEL, tokenExpireSeconds));
      final parsed = AccessToken.empty();

      expect(parsed.parse(token.build()), isTrue);
      expect(parsed.getServices(Service.RTC), isEmpty);
      expect(parsed.verifySignature(appCertificate), isTrue);
    });

    // Verifies FPA, Chat, and APaaS service payload round trips.
    test('round trips all known service payloads', () {
      final token = createToken()
        ..addService(ServiceFpa()
          ..addPrivilege(ServiceFpa.privilegeLogin, tokenExpireSeconds))
        ..addService(ServiceChat(uidString)
          ..addPrivilege(ServiceChat.privilegeUser, tokenExpireSeconds))
        ..addService(ServiceApaas(roomUuid, uidString, role)
          ..addPrivilege(ServiceApaas.privilegeRoomUser, tokenExpireSeconds));
      final parsed = AccessToken.empty();

      expect(parsed.parse(token.build()), isTrue);
      expect(parsed.verifySignature(appCertificate), isTrue);
      expect(parsed.getServices(Service.FPA).single, isA<ServiceFpa>());
      final chat = parsed.getServices(Service.CHAT).single as ServiceChat;
      expect(chat.userId, uidString);
      final apaas = parsed.getServices(Service.APAAS).single as ServiceApaas;
      expect(apaas.roomUuid, roomUuid);
      expect(apaas.userUuid, uidString);
      expect(apaas.role, role);
    });

    // Verifies the legacy low-level constructor remains usable.
    test('supports the legacy addPrivilege API', () {
      final token = AccessToken(appId, appCertificate, channelName, uid)
        ..expire = tokenExpireSeconds
        ..issueTs = issueTs
        ..salt = salt
        ..addPrivilege(
          Service.RTC,
          Privileges.JOIN_CHANNEL,
          tokenExpireSeconds,
        );
      final parsed = AccessToken.empty();

      expect(parsed.parse(token.build()), isTrue);
      final rtc = parsed.getServices(Service.RTC).single as ServiceRtc;
      expect(rtc.channelName, channelName);
      expect(rtc.uid, uidString);
    });

    // Verifies every legacy ServiceType factory and existing-service update path.
    test('supports every legacy addPrivilege service type', () {
      final serviceTypes = <int>[
        Service.RTC,
        Service.RTM,
        Service.STREAMING,
        Service.FPA,
        Service.CHAT,
        Service.FCDN,
        Service.APAAS,
        Service.RTM2,
        999,
      ];

      for (final serviceType in serviceTypes) {
        final token = AccessToken(appId, appCertificate, channelName, uid)
          ..addPrivilege(serviceType, 1, tokenExpireSeconds)
          ..addPrivilege(serviceType, 2, tokenExpireSeconds + 1);

        expect(token.services, hasLength(1));
        expect(token.services.single.serviceType, serviceType);
        expect(token.services.single.privileges, {
          1: tokenExpireSeconds,
          2: tokenExpireSeconds + 1,
        });
      }
    });

    // Verifies build validation, malformed input, and signature preconditions.
    test('rejects invalid token inputs and signatures', () {
      expect(AccessToken.empty().build(), isEmpty);
      final parsed = AccessToken.empty();
      expect(parsed.parse(null), isFalse);
      expect(parsed.parse('006invalid'), isFalse);
      expect(parsed.parse('007invalid'), isFalse);
      expect(parsed.verifySignature(appCertificate), isFalse);

      final token = createToken()..addService(createRtcService());
      expect(parsed.parse(token.build()), isTrue);
      expect(
        parsed.verifySignature('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'),
        isFalse,
      );
      expect(parsed.verifySignature('invalid'), isFalse);
      expect(parsed.verifySignature(appCertificate), isTrue);

      expect(parsed.parse('006invalid'), isFalse);
      expect(parsed.verifySignature(appCertificate), isFalse);
      expect(parsed.services, isEmpty);
    });
  });
}
