# -*- coding: utf-8 -*-
__copyright__ = "Copyright (c) Agora.io, Inc."

import os
import sys
import unittest
from unittest.mock import Mock, patch

sys.path.insert(0, os.path.abspath(
    os.path.join(os.path.dirname(__file__), '..', '..')))

from parse import check_expire, get_expire_msg, parse_token
from python3.src.AccessToken2 import AccessToken, Service, ServiceApaas, ServiceRtc


class ParseTest(unittest.TestCase):
    def setUp(self):
        """Create deterministic token fixtures shared by each parser test."""
        self.app_id = '970CA35de60c44645bbae8a215061b33'
        self.app_certificate = '5CFd2fd1755d40ecb72977518be15d3b'
        self.issue_ts = 1111111
        self.expire = 600

    def create_token(self, services):
        """Build a deterministic Token007 token containing the supplied services."""
        token = AccessToken(
            self.app_id,
            self.app_certificate,
            issue_ts=self.issue_ts,
            expire=self.expire)
        token._AccessToken__salt = 1
        for service in services:
            token.add_service(service)

        return token.build()

    def test_parse_old_single_service_token(self):
        """Parse a Token007 token generated by the old single-service format."""
        old_token = ('007eJxTYBBbsMMnKq7p9Hf/HcIX5kce9b518kCiQgSr5Zrp4X1Tu6UUGCzNDZwdjU1TUs0M'
                     'kk1MzExMk5ISUy0SjQxNDcwMk4yN3b8IMEQwMTAwMoAwBIL4CgzmKeZGxmamqUmWFsYmFqb'
                     'GluapxqnGaZYpJmYGSSkpiVwMRhYWRsYmhkbmxgDCaiTj')

        result = parse_token(old_token)

        self.assertIn('Status          : success', result)
        self.assertEqual(1, result.count('RTC (ServiceType: 1)'))
        self.assertIn('channel_name   : 7d72365eb983485397e3e3f9d460bdda', result)
        self.assertIn('uid            : 2882341273', result)

    def test_parse_repeated_service_type(self):
        """Display every service when a token repeats the same ServiceType."""
        rtc = ServiceRtc('rtc-channel', 'rtc-user')
        rtc.add_privilege(ServiceRtc.kPrivilegeJoinChannel, self.expire)
        stream_rtc = ServiceRtc('stream-channel', 'stream-user')
        stream_rtc.add_privilege(
            ServiceRtc.kPrivilegePublishDataStream, self.expire)

        result = parse_token(self.create_token([rtc, stream_rtc]))

        self.assertEqual(2, result.count('RTC (ServiceType: 1)'))
        self.assertIn('channel_name   : rtc-channel', result)
        self.assertIn('channel_name   : stream-channel', result)

    def test_parse_unknown_privilege(self):
        """Display an unknown privilege by numeric ID without failing parsing."""
        rtc = ServiceRtc('rtc-channel', 'rtc-user')
        rtc.add_privilege(99, self.expire)

        result = parse_token(self.create_token([rtc]))

        self.assertIn('Status          : success', result)
        self.assertIn('unknown (99): 600 seconds', result)

    def test_parse_non_byte_service_field(self):
        """Display integer service fields without applying byte decoding."""
        apaas = ServiceApaas('room', 'user', 1)
        apaas.add_privilege(ServiceApaas.kPrivilegeRoomUser, self.expire)

        result = parse_token(self.create_token([apaas]))

        self.assertIn('APaaS (ServiceType: 7)', result)
        self.assertIn('role           : 1', result)

    @patch('parse.time.time', return_value=100)
    def test_expiration_status(self, _):
        """Report both active and expired timestamp states."""
        self.assertEqual((False, 1), check_expire(101))
        self.assertEqual('will expire in 1 seconds', get_expire_msg(101))
        self.assertEqual((True, -1), check_expire(99))
        self.assertEqual('expired', get_expire_msg(99))

    @patch('parse.AccessToken')
    def test_handle_parser_false_result(self, access_token_class):
        """Report failure when AccessToken rejects a Token007 payload."""
        access_token_class.return_value.from_string.return_value = False

        result = parse_token('007payload')

        self.assertIn('Status : failed', result)

    @patch('parse.AccessToken')
    def test_handle_unregistered_service_display(self, access_token_class):
        """Report a parsed service type that has no display metadata."""
        unknown_service = Service(999)
        parser = Mock()
        parser.from_string.return_value = True
        parser.services = [unknown_service]
        parser._AccessToken__issue_ts = self.issue_ts
        parser._AccessToken__expire = self.expire
        parser._AccessToken__salt = 1
        parser._AccessToken__app_id = self.app_id.encode('utf-8')
        access_token_class.return_value = parser

        result = parse_token('007payload')

        self.assertIn('Unknown (ServiceType: 999)', result)

    def test_reject_unsupported_or_malformed_token(self):
        """Return clear errors for unsupported versions and malformed payloads."""
        self.assertIn('only Token007 is supported', parse_token('006invalid'))
        self.assertIn('Status : failed', parse_token('007invalid'))


if __name__ == '__main__':
    unittest.main()
